apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <namespace>-mongodb-storage-pvc  
  namespace: <namespace>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi