apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: <namespace> #namespace name
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: <mariadb image> #mariadb version
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mariadb-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef: 
              name: mariadb-configmap
              key: mysql-database
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef: 
              name: mariadb-configmap
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mariadb-secret
              key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: <namespace>-mariadb-storage-pvc #pvc name
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: <namespace> #namespace name
spec:
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
  namespace: <namespace> #namespace name
data:
  mysql-database: <database-name> #database name
  mysql-user: <database-user> #database user
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: <namespace> #namespace name
type: Opaque
data:
  mysql-root-password: <database-root-password> #database root password
  mysql-password: <database-password> #database password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <namespace>-mariadb-storage-pvc #pvc name
  namespace: <namespace> #namespace name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi